### ISSUE TITLE
решил что практика создания замечаний не помешает)

### ISSUE THREAD

**Issue by fedchanka-yuryi** [MikhniukR/Test_db#3]
if(k == 1){
                                    m1ImageView = (ImageView) findViewById(R.id.imageView2);
                                }else if(k == 2){
                                    m1ImageView = (ImageView) findViewById(R.id.imageView3);
                                }else if(k == 3){
                                    m1ImageView = (ImageView) findViewById(R.id.imageView4);
                                }else if(k == 4){
                                    m1ImageView = (ImageView) findViewById(R.id.imageView5);
                                }else{
                                    m1ImageView = (ImageView) findViewById(R.id.imageView6);
                                }

---

почему бы не использовать

---

switch (k) {
            case 1:
}

**Comment by MikhniukR** [comment]
этот вариант был сделан временно что бы хоть как то работало пока не могу заменить на нормальные динамические картинки. К новому году исправлю

P.S. Нет времени. У меня основное backend я пока его делаю.

**Comment by MikhniukR** [comment]
Все уже исправил чутка криво но работает можешь смотреть
